### ISSUE TITLE
如何修改默认端口

### ISSUE THREAD

**Issue by 359587** [a597873885/webfunny_monitor#116]
因为服务器上8010端口已经被占用，我修改了domain里面的端口,提示：
您没有使用标准端口号8010、8011，请确认你已经了解了端口号的配置规则。随意更改端口号可能导致服务无法正常运行。
那么我想彻底修改掉端口，还应该去修改那几个文件，谢谢！

**Comment by 359587** [comment]
现在会出现这个错误，不知道是否有影响
[TAILING] Tailing last 15 lines for [webfunny] process (change the value with --lines option)
/root/.pm2/logs/webfunny-error.log last 15 lines:
0|webfunny |     at Module.load (internal/modules/cjs/loader.js:928:32)
0|webfunny |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
0|webfunny |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:33:23)
0|webfunny |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
0|webfunny |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
0|webfunny |     at Module.load (internal/modules/cjs/loader.js:928:32)
0|webfunny |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
0|webfunny |     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
0|webfunny |     at internal/main/run_main_module.js:17:47 {
0|webfunny |   code: 'EADDRINUSE',
0|webfunny |   errno: -98,
0|webfunny |   syscall: 'listen',
0|webfunny |   address: '::',
0|webfunny |   port: 8010
0|webfunny | }

**Comment by a597873885** [comment]
@359587 domain文件修改后重启就行了。 你这个报错日志并非本次运行的报错，请看清日志提示
