### ISSUE TITLE
使用自定义邮箱时报错 CusUtils is not defined

### ISSUE THREAD

**Issue by Liudongge** [a597873885/webfunny_monitor#200]
### 现象描述：

按照自定义邮箱的步骤，修改useCusEmailSys更新配置并改写sendEmail方法的配置，用户注册使用邮箱时报错
{"code":500,"msg":"服务器异常，请检查 logs/error 目录下日志文件"}

### 错误日志：
*************** error log start ***************
method: POST
originalUrl:  /server/sendRegisterEmail
client ip:  ::ffff:172.16.0.177
body:
{"email":"liudg2015@icloud.com","webMonitorId":"webfunny32786"}
response time: 0
err name: ReferenceError
err message: CusUtils is not defined
err stack: ReferenceError: CusUtils is not defined
    at Function.sendEmail (/app/controllers/controllers.js:1:733029)
    at sendRegisterEmail (/app/controllers/controllers.js:1:777489)
    at dispatch (/app/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at next (/app/node_modules/koa-router/node_modules/koa-compose/index.js:45:18)
    at /app/node_modules/koa-router/lib/router.js:346:16
    at dispatch (/app/node_modules/koa-router/node_modules/koa-compose/index.js:44:32)
    at /app/node_modules/koa-router/node_modules/koa-compose/index.js:36:12
    at dispatch (/app/node_modules/koa-router/lib/router.js:351:31)
    at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    at app.use (/app/app.js:44:15)
    at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    at /app/middlreware/sqlCheck.js:33:15
    at dispatch (/app/node_modules/koa-compose/index.js:42:32)
    at parseBody.then.body (/app/node_modules/koa-bodyparser/index.js:74:14)
    at process._tickCallback (internal/process/next_tick.js:68:7)
*************** error log end ***************

**Comment by a597873885** [comment]
@Liudongge 您好，已修复，更新一下即可

**Comment by Liudongge** [comment]
已确认，问题已解决，多谢
