### ISSUE TITLE
每天的表创建

### ISSUE THREAD

**Issue by alanpeng2019** [a597873885/webfunny_monitor#22]
每天的表创建，什么时候生成。
method: POST
originalUrl:  /server/getSevenDaysLeftCount
client ip:  183.11.29.241
body: 
{"day":8,"webMonitorId":"1573010685605"}
response time: 0
err name: SequelizeDatabaseError
err message: Unknown column 'customerKeyCreatedDate' in 'where clause'
err stack: SequelizeDatabaseError: Unknown column 'customerKeyCreatedDate' in 'where clause'
    at Query.formatError (/soft/webfunny/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Query.handler [as onResult] (/soft/webfunny/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Query.execute (/soft/webfunny/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/soft/webfunny/node_modules/mysql2/lib/connection.js:408:32)
    at PacketParser.onPacket (/soft/webfunny/node_modules/mysql2/lib/connection.js:70:12)
    at PacketParser.executeStart (/soft/webfunny/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/soft/webfunny/node_modules/mysql2/lib/connection.js:77:25)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)

----------------------------------------

这个字段没有截取太长了

response time: 0
err name: SequelizeDatabaseError
err message: Data too long for column 'responseText' at row 1
err stack: SequelizeDatabaseError: Data too long for column 'responseText' at row 1
    at Query.formatError (/soft/webfunny/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Execute.handler [as onResult] (/soft/webfunny/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Execute.execute (/soft/webfunny/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/soft/webfunny/node_modules/mysql2/lib/connection.js:408:32)
    at PacketParser.onPacket (/soft/webfunny/node_modules/mysql2/lib/connection.js:70:12)
    at PacketParser.executeStart (/soft/webfunny/node_modules/mysql2/lib/packet_parser.js:75:16)

**Comment by a597873885** [comment]
@alanpeng2019 这两个问题已经知晓，会在下个版本进行修复，正常情况下，周一发布新版本
[关于数据库表创建问题](https://github.com/a597873885/webfunny_monitor/blob/master/Document.md#%E6%95%B0%E6%8D%AE%E5%BA%93%E8%A1%A8%E7%9A%84%E5%88%9B%E5%BB%BA)

**Comment by a597873885** [comment]
@alanpeng2019  关于数据库表创建问题 中我增加了一种更方便的方法，可以去参考一下，这个问题，我关闭了。
