### ISSUE TITLE
升级3.0.25之后的版本启动异常

### ISSUE THREAD

**Issue by waykyho** [a597873885/webfunny_monitor#225]
Docker镜像版本。
3.0.5正常启动，但升级之后的版本比如3.0.25，3.0.57，上报日志的服务（端口8011）启动失败。
pm2 log 可以看到一直在滚动报下面的异常日志，尝试将user表里的admin的角色设置为：superAdmin，也还是一样，请问怎么解决？

`0|webfunny  | server error Error: WHERE parameter "accessToken" has invalid "undefined" value
0|webfunny  |     at MySQLQueryGenerator.whereItemQuery (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2184:13)
0|webfunny  |     at Utils.getComplexKeys.forEach.prop (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2173:25)
0|webfunny  |     at Array.forEach (<anonymous>)
0|webfunny  |     at MySQLQueryGenerator.whereItemsQuery (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2171:35)
0|webfunny  |     at MySQLQueryGenerator.getWhereConditions (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2583:19)
0|webfunny  |     at MySQLQueryGenerator.selectQuery (/app/node_modules/sequelize/lib/dialects/abstract/query-generator.js:1315:28)
0|webfunny  |     at QueryInterface.select (/app/node_modules/sequelize/lib/query-interface.js:1122:27)
0|webfunny  |     at Promise.try.then.then.then (/app/node_modules/sequelize/lib/model.js:1756:34)
0|webfunny  |     at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
0|webfunny  |     at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)
0|webfunny  |     at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)
0|webfunny  |     at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)
0|webfunny  |     at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)
0|webfunny  |     at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)
0|webfunny  |     at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)
0|webfunny  |     at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)
0|webfunny  |     at Immediate.Async.drainQueues [as _onImmediate] (/app/node_modules/bluebird/js/release/async.js:15:14)
0|webfunny  |     at runCallback (timers.js:696:18)
0|webfunny  |     at tryOnImmediate (timers.js:667:5)
0|webfunny  |     at processImmediate (timers.js:649:5) { request:
0|webfunny  |    { method: 'GET',
0|webfunny  |     at Promise.try.then.then.then (/app/node_modules/sequelize/lib/model.js:1756:34)
0|webfunny  |      url: '/',
0|webfunny  |      header:
0|webfunny  |       { 'user-agent': 'lua-resty-http/0.10 (Lua) ngx_lua/10011',
0|webfunny  |         host: '100.72.37.143:31704' } },
0|webfunny  |   response:
0|webfunny  |    { status: 404,
0|webfunny  |      message: 'Not Found',
0|webfunny  |      header:
0|webfunny  |       { 'access-control-allow-origin': '*',
0|webfunny  |         'access-control-allow-methods': 'PUT,POST,GET,DELETE,OPTIONS',
0|webfunny  |         'access-control-allow-headers': 'access-token,webfunny-secret-code',
0|webfunny  |         'access-control-allow-credentials': 'true',
0|webfunny  |         'x-powered-by': '3.2.1',
0|webfunny  |         'content-type': 'application/json;charset=utf-8',
0|webfunny  |         connection: 'close' } },
0|webfunny  |   app: { subdomainOffset: 2, proxy: false, env: 'development' },
0|webfunny  |   originalUrl: '/',
0|webfunny  |   req: '<original node req>',
0|webfunny  |   res: '<original node res>',
0|webfunny  |   socket: '<original node socket>' }`

**Comment by a597873885** [comment]
@waykyho 去官网扫描一下微信群，我们在群里交流方便一点。 我来引导你升级。 官网地址：www.webfunny.cn
