### ISSUE TITLE
本地执行npm run test_start项目完美提示各类成功启动，访问8011脚本报错

### ISSUE THREAD

**Issue by githubmxm** [a597873885/webfunny_monitor#27]
执行npm run test_start
项目启动成功
数据库表新建成功

- 访问8010控制台报错

首页一直停留在“首次访问较慢的提示”中.....

Download the React DevTools for a better development experience: https://fb.me/react-devtools
common.359570cc2896c342576f.min.js:51 Uncaught Invariant Violation: Target container is not a DOM element.
    at l (http://localhost:8010/js/common.359570cc2896c342576f.min.js:51:318)
    at Object.render (http://localhost:8010/js/common.359570cc2896c342576f.min.js:64:203092)
    at Module.1014 (http://localhost:8010/js/javascriptError.359570cc2896c342576f.min.js:1:19462)
    at c (http://localhost:8010/js/javascriptError.359570cc2896c342576f.min.js:1:518)
    at a (http://localhost:8010/js/javascriptError.359570cc2896c342576f.min.js:1:387)
    at http://localhost:8010/js/javascriptError.359570cc2896c342576f.min.js:1:1458
    at http://localhost:8010/js/javascriptError.359570cc2896c342576f.min.js:1:1462
common.359570cc2896c342576f.min.js:64 Download the React DevTools for a better development experience: https://fb.me/react-devtools
common.359570cc2896c342576f.min.js:51 Uncaught Invariant Violation: Target container is not a DOM element.
    at l (http://localhost:8010/js/common.359570cc2896c342576f.min.js:51:318)
    at Object.render (http://localhost:8010/js/common.359570cc2896c342576f.min.js:64:203092)
    at Module.1012 (http://localhost:8010/js/javascriptErrorDetail.359570cc2896c342576f.min.js:1:19765)
    at o (http://localhost:8010/js/javascriptErrorDetail.359570cc2896c342576f.min.js:1:518)
    at r (http://localhost:8010/js/javascriptErrorDetail.359570cc2896c342576f.min.js:1:387)
    at http://localhost:8010/js/javascriptErrorDetail.359570cc2896c342576f.min.js:1:1458
    at http://localhost:8010/js/javascriptErrorDetail.359570cc2896c342576f.min.js:1:1462
common.359570cc2896c342576f.min.js:64 Download the React DevTools for a better development experience: https://fb.me/react-devtools
common.359570cc2896c342576f.min.js:51 Uncaught Invariant Violation: Target container is not a DOM element.
    at l (http://localhost:8010/js/common.359570cc2896c342576f.min.js:51:318)
    at Object.render (http://localhost:8010/js/common.359570cc2896c342576f.min.js:64:203092)
    at Module.1015 (http://localhost:8010/js/login.359570cc2896c342576f.min.js:1:7550)
    at s (http://localhost:8010/js/login.359570cc2896c342576f.min.js:1:519)
    at r (http://localhost:8010/js/login.359570cc2896c342576f.min.js:1:387)
    at http://localhost:8010/js/login.359570cc2896c342576f.min.js:1:1459
    at http://localhost:8010/js/login.359570cc2896c342576f.min.js:1:1463

**Comment by a597873885** [comment]
你好，我尝试访问了： http://localhost:8010 得到了跟你同样的错误。

访问：http://localhost:8010/home.html  就能够访问了。

PS：请认真阅读文档。

**Comment by githubmxm** [comment]
@a597873885 嗯，可以访问了.建议默认开启首页，然后好像稍微有点BUG,访问首页home的时候一直转圈圈加载数据，但是点击刷新或则切换菜单，就能正常呈现概览.

还有点就是：提示我新建应用，在项目插入探针，没有找到新建应用入口呀，在哪里呢？

**Comment by githubmxm** [comment]
好像找到了是在左上角的输入框点击弹出的创建新项目功能的步骤里实现对吧

**Comment by a597873885** [comment]
![image](https://user-images.githubusercontent.com/26519165/70228984-4cd55400-1790-11ea-82f0-712e4b2144c1.png)

好的，我会把默认打开首页的功能加上，感谢你的建议。

**Comment by githubmxm** [comment]
@a597873885 创建项目里的获取邮箱验证码也建议可以加个倒计时

**Comment by githubmxm** [comment]
我有个需求就是：现在我看提示是：7天内无数据上传将被删除应用.  是不是说探针失效和数据都没有了之后关于这个项目的.  个人觉得需求是保留历史，用户自行选择留去更好. 特别是项目上的探针有效性存在即永久除非手动更换删除

**Comment by githubmxm** [comment]
还有个新建的用户我在数据user表里没看到..是跑哪去了么

**Comment by a597873885** [comment]
7天内无数据上传将被删除应用,  这个在新版本里已经去除了。

登录注册信息是在我的的服务器上。

**Comment by githubmxm** [comment]
也就是说刚才我本地注册的信息跑你那去了呗，信息能得到安全？账号密码是否明文破解。虽然现在是本地，万一用到正式项目。。。。是否有安全问题如何消除担忧呢

**Comment by githubmxm** [comment]
还有刚才说的7天问题已经不存在 ，建议把那提示删除，误导用户和担忧导致使用问题的担忧

**Comment by a597873885** [comment]
注册是为了方便我统计使用人数，不存在安全隐患。

至于其他安全相关问题，无从答起，你自己慎重选择吧。

**Comment by githubmxm** [comment]
无从答起是个什么概念。没有就是没有，有就是有。说明就行，用户可以选择。你说呢？既然是开源项目，我想你们也是为了做好做大做优得到认可和信赖。服务更多的个人和企业为某方面体系发展提供更好的解决方案。所以每一步都很重要。当然也可以忽略我说的话哈。

**Comment by a597873885** [comment]
唉，真是拗不过你
1. 注册用户，本来是为了防止恶意注册新项目，我维护起来很麻烦。 现在不提供线上新建应用，所以用来做使用人数统计，只是提供了一个邮箱，密码随意设置，何来安全之说。
2. 日志信息都是存放在你们自己的数据库里，是否安全也只有你们知道，何来的安全问题。
3. 万一用到正式项目；本来我只是给前端开发和测试的小伙伴提供一个工具，提高排查问题的效率，并非想你们用来做商业用途。作为一个内部使用的工具即可。

**Comment by githubmxm** [comment]
没有，因为我是用户所以表达自己的看法，有不对的地方你也别在意不太懂而已纯粹用户角度。这下明白了。好的，谢谢。

**Comment by a597873885** [comment]
其实你不是第一个提出这些疑问的，只是我都懒得搭理他们，看你今天这么坚持，我才说了这么多，看来我还是要对这些安全问题做一下说明了。😂

**Comment by githubmxm** [comment]
哈哈，那这么说起来感觉自己也挺荣幸的。😀
