### ISSUE TITLE
关于使用中的问题,请教一下

### ISSUE THREAD

**Issue by hao-have-no** [a597873885/webfunny_monitor#43]
1.自动创建表功能不成功,我是以npm run local_start命令启动的
2.自定义异常统计中无法查看其他日期下的报错数据
3.在接口有数据的情况下,http://localhost:8011/server/getHttpErrorListByDay接口报错
4.用户细查功能是不是未对试用人员开启.

请您方便的时候解答一下,谢谢

**Comment by a597873885** [comment]
1.  你是windows操作系统吗？ win系统下自动创建有点问题。
2. 其他日期自定义异常，都在月统计里边点击就可以看了，这里使用有歧义，我稍后会修复一下。
3. 如果有报错，请把日志发出来。
4. 用户细查功能需要你传入USERId, 确定是否传入了。

**Comment by hao-have-no** [comment]
1.用的是ubuntu系统,需要对相关文件赋予权限吗?
3.,调用这个接口的时候http://localhost:8011/server/getHttpErrorListByDay,日志纪录的错误
.[2020-01-13T14:34:41.739] [ERROR] errorLog - 
*************** error log start ***************
method: POST
originalUrl:  /server/getHttpErrorListByDay
client ip:  ::ffff:192.168.1.13
body: 
{"timeType":0,"webMonitorId":"webfunny_1578550348520"}
response time: 0
err name: TypeError
err message: Cannot read property 'createdAt' of undefined
err stack: TypeError: Cannot read property 'createdAt' of undefined
    at HttpErrorInfoModel.(anonymous function)._0x97b839 (/opt/webfunny_monitor/controllers/controllers.js:1:41186)
*************** error log end ***************
4.window.webfunny && webfunny.wmInitUser("123456", "2.0")我是这样定义的,但是根据具体的userId会出现一下错误:
报错日志如下(查询的不是当日的表):err name: SequelizeDatabaseError
err message: Table 'webfunny_db.CustomerPV20200112' doesn't exist
err stack: SequelizeDatabaseError: Table 'webfunny_db.CustomerPV20200112' doesn't exist
    at Query.formatError (/opt/webfunny_monitor/node_modules/sequelize/lib/dialects/mysql/query.js:244:16)
    at Query.handler [as onResult] (/opt/webfunny_monitor/node_modules/sequelize/lib/dialects/mysql/query.js:51:23)
    at Query.execute (/opt/webfunny_monitor/node_modules/mysql2/lib/commands/command.js:30:14)
    at Connection.handlePacket (/opt/webfunny_monitor/node_modules/mysql2/lib/connection.js:408:32)
    at PacketParser.Connection.packetParser.p [as onPacket] (/opt/webfunny_monitor/node_modules/mysql2/lib/connection.js:70:12)
    at PacketParser.executeStart (/opt/webfunny_monitor/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.Connection.stream.on.data (/opt/webfunny_monitor/node_modules/mysql2/lib/connection.js:77:25)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by a597873885** [comment]
1. 需要授予执行权限
3. 该错误是由于表内没有接口报错的日志，有了之后就不会再报错了，这个问题，下个版本优化掉
4. 这个错误是没有表造成的，但是不影响你查询结果。

**Comment by hao-have-no** [comment]
3.今天根据用户id去查询用户行为,为什么会查询昨天的表?

**Comment by a597873885** [comment]
看下网站上的搜索示例就明白了。

**Comment by hao-have-no** [comment]
谢谢解答

**Comment by hao-have-no** [comment]
请问一下,捕获异常的数据是怎么来的?

**Comment by a597873885** [comment]
webfunny_monitor/A-monitor-code/webmonitor.js  这个是探针的源代码，可以看一下

**Comment by hao-have-no** [comment]
好的,谢谢您

**Comment by hao-have-no** [comment]
更新之后，发现还有这个问题，在查看具体日期的接口报错
[2020-01-19T08:59:24.660] [ERROR] errorLog - 
*************** error log start ***************
method: POST
originalUrl:  /server/getHttpErrorListByDay
client ip:  ::ffff:192.168.1.13
body: 
{"timeType":3,"webMonitorId":"webfunny_1578550348520"}
response time: 0
err name: TypeError
err message: Cannot read property 'createdAt' of undefined
err stack: TypeError: Cannot read property 'createdAt' of undefined
    at HttpErrorInfoModel.(anonymous function)._0x325b72 (/opt/webfunny_monitor/controllers/controllers.js:1:31313)
    at <anonymous>
*************** error log end ***************
